#!/usr/bin/env ruby

require_relative "game"
require_relative "hero"
require_relative "Menu/JobMenu"
require_relative "Menu/MainMenu"

### import all items ###

require_relative "Items/health/health"

def main
    game = Game.new
    puts "Welcome to the game !"
    puts "What is your name ?"
    
    ### Init Main Hero ###
    name = gets.chomp
    hero = Hero.new(name)
    game.addHero(hero)

    job_menu(hero)

    ### End Init Main Hero ###

    ### Test Part ###

    game.addInventory(Apple.new)
    game.addInventory(CrackingRock.new)

    ### End Test Part ###

    main_menu(game)
end

if __FILE__ == $0
    main
end